### ISSUE TITLE
Attempting to load Algomorph Advanced presets crashes VCV Rack

### ISSUE THREAD

**Issue by cosmoproductions** [anlexmatos/FM-Delexander#23]
Environment: VCV Rack 2 Pro in standalone on Windows 10
Problem 1: Attempting to load Algomorph Advanced presets causes VCV Rack to crash.
Problem 2: Attempting to load Algomorph Advanced presets fails with the error "Could not find module FM-Delexander2/Algomorph", but does not crash VCV.
These problems are 100% repro on my installation but whether it hits problem 1 or 2 appears to happen randomly.  
Please see attached files. I'm including entire log files rather than just the stack traces in case other info in there is useful to you.  The first time stamped log file and associated screen shot shows the error message dialog box. I then attempted to load a different preset which crashed VCV. The second time stamped log file shows a crash after the first attempt to load a preset.
I have no idea why substation settings are being saved between fatal signal 11 and 22, or if that's in any way related.
Please let me know if I can provide any other information.  Thanks.
[2022-01-29 182214 log.txt](https://github.com/Delexander/Volume1/files/7963201/2022-01-29.182214.log.txt)
![2022-01-29 180249](https://user-images.githubusercontent.com/82449559/151652403-0b2d801b-8a06-4415-aaf2-973ae65b9ef8.jpg)
[2022-01-29 180249 log.txt](https://github.com/Delexander/Volume1/files/7963202/2022-01-29.180249.log.txt)

**Comment by xandramax** [comment]
Thank you, this report was very helpful. I'd reproduced the crash here but not that error message, and the message points right at the issue. The preset files were referencing an old beta version of the plugin with a different title (FM-Delexander2 instead of DelexanderVol1).
